sonar.projectKey=hobsojam_test-analysis
sonar.organization=hobsojam

sonar.projectName=test-analysis

sonar.sources=tqa
sonar.exclusions=tests/**,**/__pycache__/**,**/*.pyc

sonar.sourceEncoding=UTF-8

# Coverage report is downloaded from the coverage-report artifact into coverage/
sonar.python.coverage.reportPaths=coverage/coverage.xml
